"""agregar codigo invitacion y vinculo profesor-alumno

Revision ID: b24ceae4a22b
Revises: aba11cf9ce86
Create Date: 2026-06-30 15:39:29.085459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24ceae4a22b'
down_revision: Union[str, None] = 'aba11cf9ce86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('id_profesor', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'alumnos', 'profesores', ['id_profesor'], ['id'])
    op.add_column('profesores', sa.Column('codigo_invitacion', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'profesores', ['codigo_invitacion'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profesores', type_='unique')
    op.drop_column('profesores', 'codigo_invitacion')
    op.drop_constraint(None, 'alumnos', type_='foreignkey')
    op.drop_column('alumnos', 'id_profesor')
    # ### end Alembic commands ###
